### ISSUE TITLE
benchmarks

### ISSUE THREAD

**Issue by jrevels** [jrevels/MixedModeBroadcastAD.jl#2]
Valentin and I had a nice discussion about exactly what our benchmarks will be, and this is what we settled on.

The kernel of interest is, as before, `lstm_update_c` from `src/kernels.jl`. We’ll be benchmarking these versions of it:

- Unfused w/o AD, C/CUDA version
- Fused w/o AD, C/CUDA version
- Unfused w/o AD, Julia version
- Fused w/o AD, Julia version
- Unfused w/ AD, Julia version
- Fused w/ AD, Julia version

We will use these benchmarks to demonstrate two points, ranked in order of importance:

1. That the fused AD Julia version exhibits the speedups we expect over the unfused AD Julia version. This demonstrates that the technique is generally useful in the way that we’re claiming.

2. That the (un)fused non-AD Julia code is comparable in performance to the (un)fused non-AD C/CUDA code. This demonstrates that we’re not doing anything tricky/weird by using Julia instead of C/CUDA.

**Comment by maleadt** [comment]
OK, all implemented. Issue with recording the non-fused kernel though, `no method matching +(::Record{...,Array{Float32,2}}, ::Record{...,Array{Float32,2}})` (just run `test/perf/benchmark.jl`).
I guess we need explicit implementations of these operators, but I'm not sure how those would look as `Record` doesn't seem like it can be broadcasted over (ie. `Base.+(A::Record, B::Record) = broadcast(+, A, B)` doesn't work).

EDIT: looks like that _does_ work, but then we lack `broadcast_indices` for `.=` aka `broadcast!` (eg. for `tmp1 .= σ.(tmp1)`).

**Comment by maleadt** [comment]
Some initial measurements w/o AD:

```
|   environment |   size    | fused |  elapsed  |
| -------------:|:---------:|:-----:|:---------:|
|   Julia Array |  512x512  | true  |  9.89 ms  |
| Julia CuArray |  512x512  | true  | 16.18 ms  |
|          CUDA |  512x512  | true  |  1.07 ms  |
|   Julia Array | 1024x1024 | true  | 18.56 ms  |
| Julia CuArray | 1024x1024 | true  | 438.40 us |
|          CUDA | 1024x1024 | true  | 223.34 us |
|   Julia Array | 2048x2048 | true  | 84.31 ms  |
| Julia CuArray | 2048x2048 | true  |  1.02 ms  |
|          CUDA | 2048x2048 | true  | 801.12 us |
|   Julia Array |  512x512  | false |  3.51 ms  |
| Julia CuArray |  512x512  | false | 190.30 us |
|          CUDA |  512x512  | false | 149.29 us |
|   Julia Array | 1024x1024 | false | 17.06 ms  |
| Julia CuArray | 1024x1024 | false | 698.92 us |
|          CUDA | 1024x1024 | false | 625.07 us |
|   Julia Array | 2048x2048 | false | 65.19 ms  |
| Julia CuArray | 2048x2048 | false |  2.44 ms  |
|          CUDA | 2048x2048 | false |  2.33 ms  |
```

**Comment by jrevels** [comment]
> I guess we need explicit implementations of these operators, but I'm not sure how those would look as Record doesn't seem like it can be broadcasted over (ie. Base.+(A::Record, B::Record) = broadcast(+, A, B) doesn't work).

Yup. I can implement these today.

**Comment by vchuravy** [comment]
I added a `Unfused` typed based on the lazy broadcasting PR in base...
The only problem is that branch was recently rebased and so StaticArrays is broken on that branch...
See https://github.com/jrevels/MixedModeBroadcastAD.jl/tree/vc/unfused for the changes (not fully complete yet).

**Comment by jrevels** [comment]
superseded by #15
