### ISSUE TITLE
Don't differentiate boundary states in Julia code

### ISSUE THREAD

**Issue by jrevels** [jrevels/MixedModeBroadcastAD.jl#36]
I'm having trouble justifying our differentiation of the boundary states (the `z`s) in the paper...there's really no good reason for it other than that "well we never got around to *not* differentiating them."

Our options for resolving this are either:

1. Implement variable selection in our prototype
2. Just close over the `z`s before broadcasting the kernel

I can implement option 1 myself if need be, but option 2 would be much nicer/more natural if CUDAnative can handle it. I recall being told that option 2 has performance problems since CUDAnative doesn't like it when a kernel loads from a closed-over buffer. Thoughts @maleadt / @vchuravy?

**Comment by maleadt** [comment]
You mean something like

```julia
const a = CuArray(...)
@cuda (()->(a[1]=3; nothing))()
```

(but then using `broadcast` instead of explicit `@cuda`?)

The problem here is that `@cuda` implicitly converts arguments when crossing the CPU/GPU boundary, by means of `cudaconvert`. This doesn't happen when closing over.

**Comment by maleadt** [comment]
Maybe we can make the generic closer-conversion case work though, at least without the need for CuArray/CuDeviceArray-like type conversions. I assume you want to close over boolean scalars, and don't keep them arrays as they currently are? CUDAnative doesn't handle closure conversion right now, but codegen looks reasonable so I think we could make this work.
