### ISSUE TITLE
build script

### ISSUE THREAD

**Issue by jrevels** [jrevels/MixedModeBroadcastAD.jl#7]
there's a makefile in the test directory that's currently not self-contained it seems

**Comment by maleadt** [comment]
How so, not self-contained? Just execute `make` and it should work?
Anyway, the CUDAapi-approach from #8 is better, so I've removed the Makefile.

**Comment by jrevels** [comment]
> Just execute make and it should work?

Right, that's what I wanted. Glad that #8 avoids the problem though
